spring.datasource.url=jdbc:postgresql://localhost:5432/posmanager_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=9a6747535732665a3258324671426d35516b6c434142434445464748494a4b4c4d4e4f
jwt.expiration=86400000
